#!/bin/sh
#
# @name Generic Ground Vehicle (Differential)
#
# @type Rover
# @class Rover
#
# @output Motor1 left
# @output Motor2 right
#
# @maintainer
#
# @board bitcraze_crazyflie exclude

. ${R}etc/init.d/rc.rover_defaults

param set-default BAT1_N_CELLS 6

param set-default CA_AIRFRAME 6 # Differential

param set-default PWM_AUX_FUNC2 101
param set-default PWM_AUX_FUNC3 102
